SUBMISSION_SUBMITTED = "submitted"
SUBMISSION_UNDER_REVIEW = "under_review"
SUBMISSION_APPROVED = "approved"
SUBMISSION_REJECTED = "rejected"
SUBMISSION_NEEDS_ATTESTATION = "needs_attestation"

SUBMISSION_TERMINAL_STATES = {SUBMISSION_APPROVED, SUBMISSION_REJECTED}
SUBMISSION_BENCHMARK_VALID_STATES = {SUBMISSION_APPROVED}
SUBMISSION_BENCHMARK_BLOCKED_STATES = {SUBMISSION_REJECTED, SUBMISSION_NEEDS_ATTESTATION}

RUN_QUEUED = "queued"
RUN_RUNNING = "running"
RUN_COMPLETED = "completed"
RUN_FAILED = "failed"
RUN_RELEASE_PENDING = "release_pending"
RUN_RELEASED = "released"

RUN_ACTIVE_STATES = {RUN_QUEUED, RUN_RUNNING}
RUN_RELEASE_APPROVABLE_STATES = {RUN_COMPLETED, RUN_RELEASE_PENDING}

RELEASE_DRAFT = "draft"
RELEASE_APPROVED = "approved"
RELEASE_PUBLISHED = "published"
RELEASE_ARCHIVED = "archived"

RECORD_DRAFT = "draft"
RECORD_FINALIZED = "finalized"
RECORD_ARCHIVED = "archived"
